### ISSUE TITLE
Undefined variable: config

### ISSUE THREAD

**Issue by adngdb** [jbleuzen/Picturo#13]
```
Notice: Undefined variable: config in /var/www/picturo/index.php on line 55
Not found
```

This happened while I was testing https://github.com/jbleuzen/Picturo/issues/9 from scratch again. I downloaded the .zip file, extracted it, changed the permissions and browsed to my localhost. PHP version is 5.4.6. 

Did I miss something?

**Comment by jbleuzen** [comment]
Ok, so I feel a bit noobish because I discovered via co-workers that my PHP configuration was bad...

And I can now reproduce your error...

I'll work on it !

**Comment by jbleuzen** [comment]
Should work fine now.
Sorry about that !

**Comment by adngdb** [comment]
Yep, verified fixed.
