### ISSUE TITLE
Password login don't work

### ISSUE THREAD

**Issue by ghost** [jbleuzen/Picturo#14]
Hi,
I just tried Picturo with a password. I just followed the instructions to enable this in conf/config.php. The problem is that now, I'm redirected to the page /login, which doesn't exist.
What's wrong?

Regards.

**Comment by ghost** [comment]
My bad, my nginx configuration was wrong. Here is a solution : 
    location / {
            index       index.html index.htm index.php;
            try_files   $uri @pico;
        }
       location @pico {
            rewrite     ^(.*)$ /index.php;
        }

**Comment by intermedion** [comment]
The demo login (from the documentation) still does not work; maybe the above fix was not applied to the demo?
