### ISSUE TITLE
How does one login on the demo page?

### ISSUE THREAD

**Issue by intermedion** [jbleuzen/Picturo#16]
I could not find a login link or info in the documentation on how to login to the demo.

**Comment by intermedion** [comment]
I finally found on the french site http://www.johanbleuzen.fr/blog/picturo  the info on a screenshot;
However the indicated demo login, http://www.johanbleuzen.fr/login does not work, the URL kicks the user back to the gallery page.

**Comment by jbleuzen** [comment]
Sorry for the delay.
I removed the login form as I wanted the demo to be available easily to everyone
