### ISSUE TITLE
Problem with pass-by-reference in Picturo class

### ISSUE THREAD

**Issue by ghost** [jbleuzen/Picturo#2]
Bonjour

J'utilise la version de PHP 5.4.3 et j'ai eu un problème du type :

```
Fatal error: Call-time pass-by-reference has been removed in 
core\picturo.php on line 118
```

D'après la [documentation](http://fr2.php.net/manual/fr/language.references.pass.php), il ne faut plus utiliser la signe de référence dans l'appel de la fonction, mais uniquement dans sa définition.
Jusqu'à PHP 5.3 cela levait une simple alerte, mais à partir de PHP 5.4 cela lève une erreur fatale, d'où mon problème.

En supprimant les références aux lignes 118 et 181, le problème ne se pose plus :)

Ligne 118 :

``` php
$this->get_files($resource, $folders, $imagesArray);
```

Line 181 :

``` php
$this->get_files(dirname($resource)."/", $folders, $imagesArray);
```

**Comment by jbleuzen** [comment]
Thanks was not aware of that... :+1:

**Comment by ghost** [comment]
Neither was I, until I understood why it was not working ;-)
