### ISSUE TITLE
Wrong redirection

### ISSUE THREAD

**Issue by jvoisin** [jbleuzen/Picturo#8]
I have deployed Picturo in a subfolder:

```
http://localhost/Picturo/
```

When I'm trying to go on this page, I'm redirected to

```
http://localhost/login
```

**Comment by ghost** [comment]
Yep, I have the same problem...

Maybe if the `redirect` method in `core/picturo.php` is updated like that, it will fix the problem?

``` php
private function redirect($url) {
    header('Location: ./'.$url);
    exit;
  }
```

**Comment by jbleuzen** [comment]
Ok, there is a bigger problem than the redirection...
I tried to fix the redirection, and sure it's an easy fix.

But after that fix, thumbnail generation is not working at all.
I'll need to fix that soon, but I'm working on other stuff.

**Comment by jerrywham** [comment]
idem for me. Content folder is not found because of that and background images in css have a wrong path. (Sorry for my english).

**Comment by jbleuzen** [comment]
Ok, I'll make it work in the next version I'll publish... :)

**Comment by jbleuzen** [comment]
I installed Picturo in a sub folder, edited the config "base_url" value and everything seams alright.
There may be some problems in the theme, let me know if you find something...

**Comment by jvoisin** [comment]
Now, I've got this:

```
PHP 5.5.3-1ubuntu1 Development Server started at Tue Sep 24 11:17:20 2013
Listening on http://127.0.0.1:8080
Document root is /tmp/Picturo
Press Ctrl-C to quit.
[Tue Sep 24 11:17:22 2013] PHP Fatal error:  Class 'Bramus\Router\Router' not found in /tmp/Picturo/index.php on line 13
[Tue Sep 24 11:17:22 2013] 127.0.0.1:51201 [500]: / - Class 'Bramus\Router\Router' not found in /tmp/Picturo/index.php on line 13
```

**Comment by jbleuzen** [comment]
I'd suggest to remove the vendor folder and use composer.phar to install dependencies....
But I don't know why this would solve your issue...
